module.exports = ->
  # [
  #   {
  #     index: 0,
  #     name: 'Positioned Layout',
  #     order: [
  #       'position',
  #       'top',
  #       'right',
  #       'bottom',
  #       'left',
  #       'offset-before',
  #       'offset-after',
  #       'offset-start',
  #       'offset-end',
  #       'z-index'
  #     ]
  #   },
  #   {
  #     index: 1,
  #     name: 'Flexbox',
  #     order: [
  #       'align-self',
  #       'order',
  #       'flex',
  #       'flex-grow',
  #       'flex-shrink',
  #       'flex-basis',
  #       'display: flex',
  #       'flex-flow',
  #       'flex-direction',
  #       'flex-wrap',
  #       'justify-content',
  #       'align-items',
  #       'align-content'
  #     ]
  #   },
  #   {
  #     index: 2,
  #     name: 'Basic Box',
  #     order: [
  #       'box-sizing',
  #       'display',
  #       'visibility',
  #       'float',
  #       'clear',
  #       'width',
  #       'height',
  #       'max-width',
  #       'max-height',
  #       'min-width',
  #       'padding',
  #       'padding-top',
  #       'padding-right',
  #       'padding-bottom',
  #       'padding-left',
  #       'margin',
  #       'margin-top',
  #       'margin-right',
  #       'margin-bottom',
  #       'margin-left',
  #       'overflow',
  #       'overflow-*',
  #       'resize'
  #     ]
  #   },
  #   {
  #     index: 3,
  #     name: 'Color and UI related',
  #     order: [
  #       'background',
  #       'background-*',
  #       'border',
  #       'border-color',
  #       'border-style',
  #       'border-width',
  #       'border-top',
  #       'border-right',
  #       'border-bottom',
  #       'border-left',
  #       'border-radius',
  #       'border-image',
  #       'border-image-*',
  #       'box-shadow',
  #       'caret-color',
  #       'clip',
  #       'color',
  #       'cursor',
  #       'opacity',
  #       'outline',
  #       'outline-*'
  #     ]
  #   },
  #   {
  #     index: 4,
  #     name: 'Font and Text related',
  #     order: [
  #       'alignment-adjust',
  #       'alignment-baseline',
  #       'baseline-shift',
  #       'dominant-baseline',
  #       'drop-initial-after-adjust',
  #       'drop-initial-after-align',
  #       'drop-initial-before-adjust',
  #       'drop-initial-before-align',
  #       'drop-initial-size',
  #       'drop-initial-value',
  #       'font',
  #       'font-family',
  #       'font-feature-settings',
  #       'font-kerning',
  #       'font-language-override',
  #       'font-size',
  #       'font-size-adjust',
  #       'font-stretch',
  #       'font-style',
  #       'font-synthesis',
  #       'font-variant',
  #       'font-variant-alternates',
  #       'font-variant-caps',
  #       'font-variant-east-asian',
  #       'font-variant-ligatures',
  #       'font-variant-numeric',
  #       'font-variant-position',
  #       'font-weight',
  #       'hanging-punctuation',
  #       'hyphens',
  #       'inline-box-align',
  #       'letter-spacing',
  #       'line-break',
  #       'line-height',
  #       'line-stacking',
  #       'line-stacking-ruby',
  #       'line-stacking-shift',
  #       'line-stacking-strategy',
  #       'overflow-wrap',
  #       'tab-size',
  #       'text-align',
  #       'text-align-last',
  #       'text-decoration',
  #       'text-emphasis',
  #       'text-height',
  #       'text-indent',
  #       'text-justify',
  #       'text-shadow',
  #       'text-transform',
  #       'vertical-align',
  #       'white-space',
  #       'word-break',
  #       'word-spacing',
  #       'word-wrap'
  #     ]
  #   },
  #   {
  #     index: 5,
  #     name: 'Transforms',
  #     order: [
  #       'backface-visibility',
  #       'perspective',
  #       'perspective-origin',
  #       'transform',
  #       'transform-origin',
  #       'transform-style'
  #     ]
  #   },
  #   {
  #     index: 6,
  #     name: 'Transitions and Animations',
  #     order: [
  #       'animation',
  #       'animation-*',
  #       'transition',
  #       'transition-*'
  #     ]
  #   }
  # ]
  [
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'offset-before',
    'offset-after',
    'offset-start',
    'offset-end',
    'z-index'
    'align-self',
    'order',
    'flex',
    'flex-grow',
    'flex-shrink',
    'flex-basis',
    'display: flex',
    'flex-flow',
    'flex-direction',
    'flex-wrap',
    'justify-content',
    'align-items',
    'align-content'
    'box-sizing',
    'display',
    'visibility',
    'float',
    'clear',
    'width',
    'height',
    'max-width',
    'max-height',
    'min-width',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'overflow',
    'overflow-*',
    'resize'
    'background',
    'background-*',
    'border',
    'border-color',
    'border-style',
    'border-width',
    'border-top',
    'border-right',
    'border-bottom',
    'border-left',
    'border-radius',
    'border-image',
    'border-image-*',
    'box-shadow',
    'caret-color',
    'clip',
    'color',
    'cursor',
    'opacity',
    'outline',
    'outline-*'
    'alignment-adjust',
    'alignment-baseline',
    'baseline-shift',
    'dominant-baseline',
    'drop-initial-after-adjust',
    'drop-initial-after-align',
    'drop-initial-before-adjust',
    'drop-initial-before-align',
    'drop-initial-size',
    'drop-initial-value',
    'font',
    'font-family',
    'font-feature-settings',
    'font-kerning',
    'font-language-override',
    'font-size',
    'font-size-adjust',
    'font-stretch',
    'font-style',
    'font-synthesis',
    'font-variant',
    'font-variant-alternates',
    'font-variant-caps',
    'font-variant-east-asian',
    'font-variant-ligatures',
    'font-variant-numeric',
    'font-variant-position',
    'font-weight',
    'hanging-punctuation',
    'hyphens',
    'inline-box-align',
    'letter-spacing',
    'line-break',
    'line-height',
    'line-stacking',
    'line-stacking-ruby',
    'line-stacking-shift',
    'line-stacking-strategy',
    'overflow-wrap',
    'tab-size',
    'text-align',
    'text-align-last',
    'text-decoration',
    'text-emphasis',
    'text-height',
    'text-indent',
    'text-justify',
    'text-shadow',
    'text-transform',
    'vertical-align',
    'white-space',
    'word-break',
    'word-spacing',
    'word-wrap'
    'backface-visibility',
    'perspective',
    'perspective-origin',
    'transform',
    'transform-origin',
    'transform-style'
    'animation',
    'animation-*',
    'transition',
    'transition-*'
  ]
